Code review
Tahirbhalli/library pull request #1
Opened 2020-06-23 14:56 UTC by Tahirbhalli

> build with
  > html
  > bootstrap
  > javascript

2020-06-23 16:01 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-23 16:01 UTC, bellom commented on script/data.js
> +}
Let's separate the DOM from application logic, you can create another file for DOM.

![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

2020-06-23 16:01 UTC, bellom commented on index.html
> +                </form>
Kindly validate your form, users should not be able to add an empty form.

2020-06-23 16:01 UTC, bellom commented on script/data.js
> +    books = [new Book('javascript', 'Ghosh', 10, 'Read'), new Book('css', 'Ghosh', 10, 'Read'), new Book('html', 'Ghosh', 10, 'Read')];
We need to add a `remove` button to each book,  you can easily make use of `data-atrr`
![image](https://user-images.githubusercontent.com/31897434/85426687-b709e680-b572-11ea-9895-2ecd52622983.png)
https://www.theodinproject.com/courses/javascript/lessons/library

2020-06-23 16:13 UTC, bellom commented on script/data.js
> +class Book {
we are missing the render function, I can see your `getBook` function, but one of the project requirement is to have a render function that loops through the book array and displays each book on the page.
Kindly create the render function as we both know all other students follow this project guideline too. 👍 
![image](https://user-images.githubusercontent.com/31897434/85427772-2207ed00-b574-11ea-8f7b-dd9f2164572b.png)
https://www.theodinproject.com/courses/javascript/lessons/library

2020-06-23 18:57 UTC, shloch requested changes
## Hello @Tahirbhalli , 

### changes required]

please control the form like former TSE said, control submission of empty forms
![book](https://user-images.githubusercontent.com/40712459/85445856-b9c50580-b58b-11ea-9a71-4631d2893f94.gif)

let's do this

2020-06-24 09:53 UTC, maelfosso approved these changes
# Congratulations :red_circle: 

Thank  you for applying the suggested changes. It's working now like a charm :smile: 
You can merge it :+1: 

Good continuation :handshake: 

Mael FOSSO

2020-06-24 10:04 UTC, merged